[build]
builder = "nixpacks"
buildCommand = "cd etc/build && ant war"

[deploy]
startCommand = "java -jar build/draw.war"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on-failure"

[variables]
PORT = "8080"
